### ISSUE TITLE
Agent fails to start on hostnames not compliant with RFC 1123

### ISSUE THREAD

**Issue by dsahni** [DataDog/datadog-unix-agent#43]
Perhaps hostnames that include underscores can be automatically replaced with hyphens in order for the agent to start?

The current workaround is to add a `hostname` parameter in the `datadog.yaml` configuration file that specified a hostname without underscores.

Here is the error message:

```
 > ./agent.py start
2018-08-09 12:24:20,918 | INFO | dd.agent | utils.pidfile(pidfile.py:36) | Pid file is: /tmp/datadog-unix-agent.pid
2018-08-09 12:24:20,919 | INFO | dd.agent | root(agent.py:227) | Start daemon
2018-08-09 12:24:20,919 | INFO | dd.agent | utils.daemon(daemon.py:95) | Starting...
2018-08-09 12:24:20,920 | DEBUG | dd.agent | utils.process(process.py:126) | Popen(['/bin/hostname', '-s'], stdout = -1) called
2018-08-09 12:24:20,931 | WARNING | dd.agent | utils.hostname(hostname.py:33) | Hostname: l490vp026_pub is not complying with RFC 1123
2018-08-09 12:24:20,931 | WARNING | dd.agent | utils.hostname(hostname.py:33) | Hostname: l490vp026_pub is not complying with RFC 1123
2018-08-09 12:24:20,931 | CRITICAL | dd.agent | utils.hostname(hostname.py:70) | Unable to reliably determine host name. You can define one in datadog.conf or in your hosts file
Traceback (most recent call last):
  File "./agent.py", line 248, in <module>
    sys.exit(main())
  File "./agent.py", line 228, in main
    agent.start(foreground=foreground)
  File "/opt/datadog/datadog-unix-agent/utils/daemon.py", line 114, in start
    self.run()
  File "./agent.py", line 133, in run
    hostname = get_hostname()
  File "/opt/datadog/datadog-unix-agent/utils/hostname.py", line 71, in get_hostname
    raise Exception('Unable to reliably determine host name. You can define one in datadog.conf or in your hosts file')
Exception: Unable to reliably determine host name. You can define one in datadog.conf or in your hosts file
```

**Comment by truthbk** [comment]
Should be made a little more graceful by https://github.com/DataDog/datadog-unix-agent/pull/42
